[graph]
targets = [
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-apple-darwin",
]

all-features = false
no-default-features = false
#features = []

[output]
feature-depth = 1

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "BSL-1.0", "MIT", "Unicode-DFS-2016"]
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
